<?php

return [
    /**
     * The namespace for repositories generated by the make:repository command.
     */
    'namespace' => 'App\\Repositories',

    /**
     * The base repository class to extend new repositories with.
     */
    'base' => \CZim\Repository\BaseRepository::class,

    /**
     * The suffix of each and every Repository.
     * This will be subtracted to generate de propable model class names.
     */
    'suffix' => 'Repository',

    /**
     * The locations where Eloquent models are stored.
     */
    'models' => 'App',
];
